@BlackRoseVPNManager_HostAddress = http://localhost:5073

### Register API
POST {{BlackRoseVPNManager_HostAddress}}/api/Auth/register
Content-Type: application/json
Accept: application/json

{
  "Username": "Pourii83",
  "Password": "Sensilag1383"
}

### Login API
POST {{BlackRoseVPNManager_HostAddress}}/api/Auth/login
Content-Type: application/json
Accept: application/json

{
  "Username": "testuser",
  "Password": "testpassword"
}
###check-auth API
Get {{BlackRoseVPNManager_HostAddress}}/api/Auth/check-auth
Accept: application/json